config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :multibanco_providers, :except => [:show, :destroy] do
      put :toggle_activation, :on => :member
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :payments, only: [] do
        get 'capture_mb_payment', on: :collection
      end
    end
  end
end

app/models/spree/multibanco_provider.rb
module Spree
  class MultibancoProvider < ActiveRecord::Base
  	has_many :payments

    validates :name, :entity, :subentity, presence: true
    validates_uniqueness_of :subentity, scope: :entity

    scope :active, -> { where(active: true) }
  end
end

app/models/spree_multibanco/spree/multibanco_provider.rb
module SpreeMultibanco::Spree
  class MultibancoProvider < ActiveRecord::Base
  	has_many :payments

    validates :name, :entity, :subentity, presence: true
    validates_uniqueness_of :subentity, scope: :entity

    scope :active, -> { where(active: true) }
  end
end

app/controllers/spree/admin/multibanco_providers_controller.rb
module Spree
  module Admin
    class MultibancoProvidersController < ResourceController
      def index
        @search = Spree::MultibancoProvider.ransack(params[:q])
        @multibanco_providers = @search.result.page(params[:page])
      end

      def toggle_activation
        @success = @multibanco_provider.toggle!(:active)
      end
    end
  end
end

app/controllers/spree_multibanco/spree/admin/multibanco_providers_controller.rb
module SpreeMultibanco::Spree
  module Admin
    class MultibancoProvidersController < ResourceController
      def index
        @search = Spree::MultibancoProvider.ransack(params[:q])
        @multibanco_providers = @search.result.page(params[:page])
      end

      def toggle_activation
        @success = @multibanco_provider.toggle!(:active)
      end
    end
  end
end

app/helpers/spree/admin/multibanco_providers_helper.rb
module Spree
  module Admin
    module MultibancoProvidersHelper

      def multibanco_provider_status(provider)
        provider.active? ? Spree.t(:active) : Spree.t(:inactive)
      end

      def action_to_toggle_multibanco_provider_status(provider)
        provider.active? ? Spree.t(:deactivate) : Spree.t(:activate)
      end

    end
  end
end

app/views/spree/admin/multibanco_providers/_form.html.erb
<div data-hook="admin_inside_multibanco_provider_form" class="row">
  <div class="col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:multibanco_provider_name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :entity, class: ['form-group'] do %>
      <%= f.label :entity, Spree.t(:multibanco_provider_entity) %> <span class="required">*</span>
      <%= f.text_field :entity, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :subentity, class: ['form-group'] do %>
      <%= f.label :subentity, Spree.t(:multibanco_provider_subentity) %> <span class="required">*</span>
      <%= f.text_field :subentity, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :active, class: ['form-group'] do %>
      <%= f.check_box :active %>
      <%= f.label :active, Spree.t(:multibanco_provider_active) %>
    <% end %>

  </div>
</div>

app/views/spree/admin/multibanco_providers/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:edit_multibanco_provider) %>
<% end %>

<div data-hook="admin_multibanco_provider_edit_form">
  <%= form_for [:admin, @multibanco_provider] do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div data-hook="admin_multibanco_provider_edit_form_buttons">
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/multibanco_providers/index.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t(:listing_multibanco_providers) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_multibanco_provider), new_admin_multibanco_provider_path, :class => "btn-success", :icon => 'add', :id => 'admin_new_multibanco_provider_link'%>
<% end %>

<%= paginate @multibanco_providers %>

<table class='table' id="listing_multibanco_providers" data-hook>
  <thead>
    <th><%= sort_link @search, :name, Spree.t(:multibanco_provider_name) %></th>
    <th><%= sort_link @search, :entity, Spree.t(:multibanco_provider_entity) %></th>
    <th><%= sort_link @search, :subentity, Spree.t(:multibanco_provider_subentity) %></th>
    <th><%= sort_link @search, :active, Spree.t(:multibanco_provider_active) %></th>
  </thead>

  <tbody>
    <% @multibanco_providers.each do |provider| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= provider.name %></td>
        <td class="align-center"><%= provider.entity %></td>
        <td class="align-center"><%= provider.subentity %></td>
        <td class="align-center" id='active-status-<%= provider.id %>'><%= multibanco_provider_status(provider) %></td>
        <td class="actions"><%= link_to action_to_toggle_multibanco_provider_status(provider), toggle_activation_admin_multibanco_provider_path(provider), :remote => true, :method => :put %></td>
        <td class="actions"><%= link_to_edit provider, :no_text => true, :class => 'edit' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/multibanco_providers/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_multibanco_provider) %>
<% end %>

<div data-hook="admin_multibanco_provider_new_form">
  <%= form_for [:admin, @multibanco_provider] do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div data-hook="admin_multibanco_provider_new_form_buttons">
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/multibanco_providers/toggle_activation.js.erb
<% if @success %>
  $('#active-status-<%= @multibanco_provider.id %>').text('<%= multibanco_provider_status(@multibanco_provider) %>')
  $('a[href="<%= toggle_activation_admin_multibanco_provider_path(@multibanco_provider) %>"]').text('<%= action_to_toggle_multibanco_provider_status(@multibanco_provider) %>')
<% else %>
  alert('<%= @multibanco_provider.errors.full_messages.to_sentence %>')
<% end %>